### ISSUE TITLE
$ in salt throws FormatException: Crypt string invalid format

### ISSUE THREAD

**Issue by binupa** [hoylen/dart-crypt#4]
If you use $ in salt string, the toString() shows $ as is. That's OK, as long as the reverse parsing is done properly, with this risk kept in mind. For example, If the string split has more tokens than expected, the additional tokens need to be joined using $ to reconstruct the salt.

```dart
// Insert $ in salt as well as key
var hash = Crypt.sha512('E429@LF%h7*(VGm\$v', rounds: 1500, salt: 'DG60s2#d\$vgh').toString();
print('hash: $hash');
var c = Crypt(hash); // Throws exception
```

**Comment by hoylen** [comment]
Thank you for that observation.

I have now added a check to _crypt v4.3.0_, to prevent passing in a salt value that contains a dollar sign. This prevents the library _creating_ a value that uses such a salt.

But I have not changed its implementation of _parsing_ a value (created by some other implementation) that happens to use a dollar sign in its salt. This implementation does use a string _split_ operation for that.

I had a quick look at the document describing the _Unix Crypt Format_ and it is hideously complex! This is because the format has evolved over time. The original format didn't have support for rounds or different algorithms: they just kept adding parts to a format that originally wasn't designed to be extensible.

This is an interesting edge case to think about. But is unlikely to be encountered, since anyone implementing a random salt generator (and knowing about the crypt format) would avoid generating the dollar sign in the salt.
